# Generated by Django 3.2.6 on 2021-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turistcios/outra'),
        ),
    ]
